//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

impl_payload! {
    /// Replaces the token of a bot that is managed by the current bot. The current bot must have permissions to manage the bot, granted using the @BotFather Mini App. Returns the new token of the bot as a String on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub ReplaceManagedBotToken (ReplaceManagedBotTokenSetters) => String {
        required {
            /// Unique identifier of the bot
            pub user_id: u64,
        }
    }
}
