//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{KeyboardButton, PreparedKeyboardButton};

impl_payload! {
    /// Use this method to store a keyboard button that can be added by the bot to a reply keyboard of an opener of a Mini App. Returns a [`PreparedKeyboardButton`] object.
    ///
    /// [`PreparedKeyboardButton`]: crate::types::PreparedKeyboardButton
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SavePreparedKeyboardButton (SavePreparedKeyboardButtonSetters) => PreparedKeyboardButton {
        required {
            /// A JSON-serialized object describing the keyboard button to be added.
            pub button: KeyboardButton,
        }
    }
}
