//! Generated by `codegen_payloads`, do not edit by hand.

use serde::Serialize;

use crate::types::{ChatId, MessageEntity, ParseMode, ThreadId, True};

impl_payload! {
    /// Use this method to stream a partial message to a user while the message is being generated. Note that the streamed draft is ephemeral and acts as a temporary 30-second preview - once the output is finalized, you must call sendMessage with the complete message to persist it in the user's chat. Returns True on success.
    #[derive(Debug, PartialEq, Eq, Hash, Clone, Serialize)]
    pub SendMessageDraft (SendMessageDraftSetters) => True {
        required {
            /// Unique identifier for the target private chat
            pub chat_id: ChatId [into],
            /// Unique identifier of the message draft; must be non-zero. Changes of drafts with the same identifier are animated.
            pub draft_id: i32,
        }
        optional {
            /// Unique identifier for the target message thread
            pub message_thread_id: ThreadId,
            /// Text of the message to be sent, 0-4096 characters after entities parsing. Pass an empty text to show a "Thinking…" placeholder.
            pub text: String [into],
            /// Mode for parsing entities in the message text. See formatting options for more details.
            pub parse_mode: ParseMode,
            /// A JSON-serialized list of special entities that appear in message text, which can be specified instead of parse_mode
            pub entities: Vec<MessageEntity> [collect],
        }
    }
}
